language: python
python:
  - "3.7"
  - "3.8"
env:
  - APPDIR=dash-app
  - APPDIR=testdata-writer
# command to install dependencies
install:
  - pip install -r $APPDIR/requirements-dev.txt
# command to run test
script:
  - pylint $APPDIR
  - black --check $APPDIR
